version: '3.7'

services:
  worker:
    image: kjwon15/qdon-prefetch
    build: .
    env_file: .env
    deploy:
      update_config:
        order: start-first
    secrets:
      - source: qdon-prefetch_url
        target: MASTODON_URL
      - source: qdon-prefetch_token
        target: MASTODON_ACCESS_TOKEN

secrets:
  qdon-prefetch_url:
    external: true
  qdon-prefetch_token:
    external: true
